### ISSUE TITLE
Adding Table object support

### ISSUE THREAD

**Issue by scaryclam** [heavenshell/py-sqlalchemy_seed#60]
Hi,

I'm using your library to help seed some data into our local environments. We have some fairly complex data structures going on, with a lot of M2M relations.

The relationships are Table objects, rather than models and so don't work with the model creation. The creation of the relation tables themselves isn't an issue (that's already taken care of my sqlalchemy create_all), but rather the insertion of seed data to create the relations.

We have a simple work around, which shouldn't clutter things up much. Would you be interested in me submitting a PR with a proposed feature for allowing Table inserts?

**Comment by heavenshell** [comment]
Thank you for comment and suggestion!

I don't use Table objects but sounds interesting.
Off course PRs are very welcome!

**Comment by heavenshell** [comment]
Waiting PRs 😉
